export const THEME_PRESETS = {
  BAZAAR_ELECTRONICS: { code: "BAZAAR_ELECTRONICS", nameAr: "بيتا للإلكترونيات", nameEn: "Beta Electronics", description: "تخطيط تقني مستوحى من Gadget 1 وGadget 2.", sourceDemo: "gadget-1 / gadget-2", recommendedActivities: ["ELECTRONICS_COMPUTERS"], tokens: { primary: "#2B7FFF", secondary: "#0F3460", accent: "#FA8C16", background: "#F8FAFC", surface: "#FFFFFF", text: "#1F2937", muted: "#6B7280", border: "#E5E7EB", radius: 12, shadow: "0 4px 16px rgba(43, 52, 69, .10)", font: "Arial, Tahoma, sans-serif", density: "comfortable" }, variants: { header: "shop-layout-1", navigation: "secondary-categories", homepage: "commerce", productCard: "electronics", footer: "footer-1", mobile: "bottom-navigation", category: "icon-grid" } },
  BAZAAR_FASHION: { code: "BAZAAR_FASHION", nameAr: "بازار للأزياء", nameEn: "Bazaar Fashion", description: "تخطيط بصري يركز على الصور والمنتج.", sourceDemo: "fashion-1", recommendedActivities: ["FASHION"], tokens: { primary: "#D23F57", secondary: "#141850", accent: "#F4B500", background: "#FFFFFF", surface: "#FFFFFF", text: "#1F2937", muted: "#6B7280", border: "#E5E7EB", radius: 10, shadow: "0 4px 16px rgba(20, 24, 80, .10)", font: "Arial, Tahoma, sans-serif", density: "comfortable" }, variants: { header: "shop-layout-1", navigation: "secondary-categories", homepage: "image-first", productCard: "fashion", footer: "footer-1", mobile: "bottom-navigation", category: "image-grid" } },
  BAZAAR_GROCERY: { code: "BAZAAR_GROCERY", nameAr: "بيتا للسوبرماركت", nameEn: "Beta Grocery", description: "تخطيط سريع للفئات والشراء المتكرر مستوحى من Grocery 4.", sourceDemo: "grocery-4", recommendedActivities: ["GROCERY"], tokens: { primary: "#00C950", secondary: "#0D542B", accent: "#FA8C16", background: "#F8FAFC", surface: "#FFFFFF", text: "#1F2937", muted: "#6B7280", border: "#DCFCE7", radius: 10, shadow: "0 4px 16px rgba(0, 130, 54, .10)", font: "Arial, Tahoma, sans-serif", density: "compact" }, variants: { header: "shop-layout-3", navigation: "category-drawer", homepage: "quick-shop", productCard: "grocery", footer: "footer-2", mobile: "bottom-navigation", category: "icon-grid" } },
  BAZAAR_HEALTH: { code: "BAZAAR_HEALTH", nameAr: "بازار للصحة والعناية", nameEn: "Bazaar Health", description: "ألوان هادئة ومعلومات مرتبة مستوحاة من Health & Beauty.", sourceDemo: "health-beauty / medical", recommendedActivities: ["HEALTH", "PHARMACY"], tokens: { primary: "#2B7FFF", secondary: "#0E3D56", accent: "#68C0C0", background: "#F0FAFA", surface: "#FFFFFF", text: "#1F2937", muted: "#4B5563", border: "#CCEFF0", radius: 12, shadow: "0 4px 16px rgba(14, 61, 86, .10)", font: "Arial, Tahoma, sans-serif", density: "comfortable" }, variants: { header: "shop-layout-3", navigation: "side-category", homepage: "trust-first", productCard: "health", footer: "footer-2", mobile: "bottom-navigation", category: "icon-grid" } },
  BAZAAR_GIFT: { code: "BAZAAR_GIFT", nameAr: "بازار للهدايا", nameEn: "Bazaar Gift", description: "مظهر احتفالي دافئ مستوحى من Gift Shop.", sourceDemo: "gift-shop", recommendedActivities: ["GIFT"], tokens: { primary: "#B86667", secondary: "#532727", accent: "#F4B500", background: "#FAF0F1", surface: "#FFFFFF", text: "#1F2937", muted: "#6B7280", border: "#EEDADA", radius: 12, shadow: "0 4px 16px rgba(83, 39, 39, .10)", font: "Arial, Tahoma, sans-serif", density: "comfortable" }, variants: { header: "shop-layout-3", navigation: "category-drawer", homepage: "campaigns", productCard: "gift", footer: "footer-1", mobile: "bottom-navigation", category: "image-grid" } },
  BAZAAR_GENERAL: { code: "BAZAAR_GENERAL", nameAr: "بيتا العام", nameEn: "Beta General", description: "تخطيط متوازن مستوحى من Market 2 للمتاجر متعددة الأنشطة.", sourceDemo: "market-2", recommendedActivities: ["GENERAL_STORE"], tokens: { primary: "#4BB4B4", secondary: "#0E3D56", accent: "#FA8C16", background: "#FFFFFF", surface: "#FFFFFF", text: "#1F2937", muted: "#6B7280", border: "#E5E7EB", radius: 10, shadow: "0 4px 16px rgba(14, 61, 86, .08)", font: "Arial, Tahoma, sans-serif", density: "comfortable" }, variants: { header: "shop-layout-1", navigation: "secondary-categories", homepage: "balanced", productCard: "balanced", footer: "footer-1", mobile: "bottom-navigation", category: "icon-grid" } }
};
export const THEME_PRESET_KEYS = Object.keys(THEME_PRESETS);
export const LEGACY_THEME_MAP = { default: "BAZAAR_GENERAL", electronics: "BAZAAR_ELECTRONICS", dark: "BAZAAR_ELECTRONICS", fashion: "BAZAAR_FASHION", green: "BAZAAR_GROCERY", health: "BAZAAR_HEALTH", gift: "BAZAAR_GIFT", red: "BAZAAR_FASHION", orange: "BAZAAR_ELECTRONICS", gold: "BAZAAR_GIFT", paste: "BAZAAR_HEALTH", bluish: "BAZAAR_GENERAL", yellow: "BAZAAR_GROCERY" };
export function normalizeThemeKey(value) { const key = String(value || "").trim(); return THEME_PRESETS[key]?.code || THEME_PRESETS[key.toUpperCase()]?.code || LEGACY_THEME_MAP[key.toLowerCase()] || "BAZAAR_GENERAL"; }
