export const THEME_PRESETS = {
  DEFAULT: { code: 'DEFAULT', nameAr: 'الافتراضي', nameEn: 'Default', description: 'واجهة متوازنة مناسبة لمعظم المتاجر.', preview: '#2563eb', tokens: { primary: '#2563eb', secondary: '#1e3a8a', accent: '#f59e0b', background: '#f8fafc', surface: '#ffffff', text: '#1f2937', muted: '#64748b', border: '#e2e8f0', radius: 12, shadow: '0 8px 24px rgba(15, 23, 42, .08)', font: 'Arial, Tahoma, sans-serif', density: 'comfortable' }, layoutOptions: { headerVariant: 'clean', homepageVariant: 'balanced', cardVariant: 'standard', footerVariant: 'standard' } },
  TECH_MODERN: { code: 'TECH_MODERN', nameAr: 'تقني عصري', nameEn: 'Tech Modern', description: 'ألوان تقنية واضحة لمتاجر الكمبيوتر والإلكترونيات.', preview: '#2563eb', tokens: { primary: '#2563eb', secondary: '#0f2747', accent: '#f59e0b', background: '#f5f8fc', surface: '#ffffff', text: '#10233f', muted: '#64748b', border: '#dbe5f0', radius: 10, shadow: '0 10px 28px rgba(15, 39, 71, .10)', font: 'Arial, Tahoma, sans-serif', density: 'comfortable' }, layoutOptions: { headerVariant: 'tech', homepageVariant: 'commerce', cardVariant: 'tech', footerVariant: 'navy' } },
  DARK_TECH: { code: 'DARK_TECH', nameAr: 'تقني داكن', nameEn: 'Dark Tech', description: 'مظهر داكن احترافي مع تباين مناسب.', preview: '#38bdf8', tokens: { primary: '#38bdf8', secondary: '#1e293b', accent: '#fbbf24', background: '#0b1220', surface: '#111c2e', text: '#edf5ff', muted: '#a8b6ca', border: '#263954', radius: 10, shadow: '0 10px 28px rgba(0, 0, 0, .28)', font: 'Arial, Tahoma, sans-serif', density: 'compact' }, layoutOptions: { headerVariant: 'dark', homepageVariant: 'commerce', cardVariant: 'dark', footerVariant: 'dark' } },
  MINIMAL_LIGHT: { code: 'MINIMAL_LIGHT', nameAr: 'فاتح بسيط', nameEn: 'Minimal Light', description: 'واجهة خفيفة ونظيفة للمحلات العامة.', preview: '#0f766e', tokens: { primary: '#0f766e', secondary: '#134e4a', accent: '#d97706', background: '#ffffff', surface: '#ffffff', text: '#1f2937', muted: '#6b7280', border: '#e5e7eb', radius: 6, shadow: '0 4px 16px rgba(15, 23, 42, .06)', font: 'Arial, Tahoma, sans-serif', density: 'comfortable' }, layoutOptions: { headerVariant: 'minimal', homepageVariant: 'minimal', cardVariant: 'minimal', footerVariant: 'standard' } }
};
export const THEME_PRESET_KEYS = Object.keys(THEME_PRESETS);
export const LEGACY_THEME_MAP = { default: 'DEFAULT', electronics: 'TECH_MODERN', dark: 'DARK_TECH', fashion: 'MINIMAL_LIGHT', red: 'DEFAULT', green: 'MINIMAL_LIGHT', orange: 'TECH_MODERN', gold: 'MINIMAL_LIGHT', gift: 'MINIMAL_LIGHT', paste: 'MINIMAL_LIGHT', health: 'MINIMAL_LIGHT', bluish: 'TECH_MODERN', yellow: 'TECH_MODERN' };
export function normalizeThemeKey(value) { const key = String(value || '').trim(); return THEME_PRESETS[key]?.code || THEME_PRESETS[key.toUpperCase()]?.code || LEGACY_THEME_MAP[key.toLowerCase()] || 'DEFAULT'; }
